- name: Copy and Apply Kubernetes YAML
  hosts: 192.168.137.135  
  gather_facts: false
  become: true
 
  tasks:
    - name: Copy test.yaml to remote host
      copy:
        src: k8s-deply.yaml  
        dest: k8s-deply.yaml  
        mode: 0644
 
    - name: Copy secret.yaml to remote host
      copy:
        src: secret.yaml
        dest: secret.yaml  
        mode: 0645
 
    - name: Apply test.yaml using kubectl
      command: "kubectl apply -f k8s-deply.yaml"
 
    - name: Apply secret.yaml using kubectl
      command: "kubectl apply -f secret.yaml"


